/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/图论': RouteRecordInfo<
      '/posts/图论',
      '/posts/%E5%9B%BE%E8%AE%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/复杂度分析与STL选讲/': RouteRecordInfo<
      '/posts/复杂度分析与STL选讲/',
      '/posts/%E5%A4%8D%E6%9D%82%E5%BA%A6%E5%88%86%E6%9E%90%E4%B8%8ESTL%E9%80%89%E8%AE%B2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/子序列自动机': RouteRecordInfo<
      '/posts/子序列自动机',
      '/posts/%E5%AD%90%E5%BA%8F%E5%88%97%E8%87%AA%E5%8A%A8%E6%9C%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/数论': RouteRecordInfo<
      '/posts/数论',
      '/posts/%E6%95%B0%E8%AE%BA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git': RouteRecordInfo<
      '/posts/git',
      '/posts/git',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-valaxy': RouteRecordInfo<
      '/posts/hello-valaxy',
      '/posts/hello-valaxy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/linux操作': RouteRecordInfo<
      '/posts/linux操作',
      '/posts/linux%E6%93%8D%E4%BD%9C',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/python虚拟环境': RouteRecordInfo<
      '/posts/python虚拟环境',
      '/posts/python%E8%99%9A%E6%8B%9F%E7%8E%AF%E5%A2%83',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vscode': RouteRecordInfo<
      '/posts/vscode',
      '/posts/vscode',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.4_mag_504066cbfad75f6716cfc76600226f28/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.4_@babel+parser_af8debf82d1e16a7aac18837d0cf58af/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.4_mag_504066cbfad75f6716cfc76600226f28/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.4_mag_504066cbfad75f6716cfc76600226f28/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/图论.md': {
      routes:
        | '/posts/图论'
      views:
        | never
    }
    'pages/posts/复杂度分析与STL选讲/index.md': {
      routes:
        | '/posts/复杂度分析与STL选讲/'
      views:
        | never
    }
    'pages/posts/子序列自动机.md': {
      routes:
        | '/posts/子序列自动机'
      views:
        | never
    }
    'pages/posts/数论.md': {
      routes:
        | '/posts/数论'
      views:
        | never
    }
    'pages/posts/git.md': {
      routes:
        | '/posts/git'
      views:
        | never
    }
    'pages/posts/hello-valaxy.md': {
      routes:
        | '/posts/hello-valaxy'
      views:
        | never
    }
    'pages/posts/linux操作.md': {
      routes:
        | '/posts/linux操作'
      views:
        | never
    }
    'pages/posts/python虚拟环境.md': {
      routes:
        | '/posts/python虚拟环境'
      views:
        | never
    }
    'pages/posts/vscode.md': {
      routes:
        | '/posts/vscode'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
